349 ux guide
18F/approaches pull request #44
Opened 2023-07-28 21:35 UTC by AnitaYCheng

## Changes proposed in this pull request:

Migrated:
- `about.md`
- All pages in `/design/`
- All pages in `/our-approach/`
- All pages in '/research/'

**Note**: I left `{{site.baseurl}}`s for pages in the UX Guide that have not been moved yet. Some pages in `/resources/` have permalinks in `/research/` but I can clean that up that when I move resources in [#350](https://github.com/18F/TLC-crew/issues/350).

2023-07-31 20:59 UTC, igorkorenfeld requested changes
Great work this is a lot of pages. 

A few notes on spaces, an image, and links. 

Another thing I noticed is that a lot of the pages contain a "description" in the front matter, and I don't believe this is currently being used anywhere. Perhaps it should? If so we should make another ticket for it.

2023-07-31 20:59 UTC, igorkorenfeld commented on content/ux-guide/design/build-a-prototype.md
> +- Validate a [design hypothesis [18F design methods]](https://methods.18f.gov/decide/design-hypothesis/)
Maybe worthwhile to make methods a '/TODO/' link because we are going to replatform them as well.

2023-07-31 20:59 UTC, igorkorenfeld commented on content/ux-guide/design/build-a-prototype.md
> +- [Wireframes [18F design methods]](https://methods.18f.gov/make/wireframing/) are preliminary blueprints that can help teams align on structure, placement, and hierarchy for a product or service
Same applies here

2023-07-31 20:59 UTC, igorkorenfeld commented on content/ux-guide/design/build-a-prototype.md
> +[Prototypes [18F design methods]](https://methods.18f.gov/make/prototyping/) provide realistic depictions of a user experience, so it’s important to carefully consider the elements that go into yours
I won't flag them all for now, but last one.

2023-07-31 20:59 UTC, igorkorenfeld commented on content/ux-guide/about.md
> +    parent: ux-guide
For consistency, could you change these nested elements to use 2 space indents, to be consistent with the other guides?

2023-07-31 20:59 UTC, igorkorenfeld commented on content/ux-guide/design/build-a-prototype.md
> +    parent: ux-guide-design
Change to 2 space indents for consistency.

2023-07-31 20:59 UTC, igorkorenfeld commented on content/ux-guide/design/build-a-prototype.md
> +- text: Communicating with prototypes
Need to indent these by 2 spaces

2023-07-31 20:59 UTC, igorkorenfeld commented on content/ux-guide/design/index.md
> +    parent: ux-guide-design
2 spaces

2023-07-31 20:59 UTC, igorkorenfeld commented on content/ux-guide/design/use-a-design-system.md
> +    parent: ux-guide-design
2 spaces

2023-07-31 20:59 UTC, igorkorenfeld commented on content/ux-guide/our-approach/defining-design.md
> +    parent: ux-guide-approach
2 spaces

2023-07-31 20:59 UTC, igorkorenfeld commented on content/ux-guide/our-approach/defining-design.md
> +- text: A series of intentional decisions
2 spaces here

2023-07-31 20:59 UTC, igorkorenfeld commented on content/ux-guide/our-approach/defining-design.md
> +## Design is a series of intentional decisions
Nice catch on the heading level!

2023-07-31 20:59 UTC, igorkorenfeld commented on content/ux-guide/our-approach/defining-design.md
> +{% image_with_class "assets/ux-guide/iterative-design.png"  "A conceptual image that describes iterative design. The phrase 'iterative design' is surrounded by four labels connected by a circle of cl
`image_with_class` takes 3 arguments in the order `<file>`  `<class>` `<alt-text>`, so currently the alt text is being used as the class names. You'll need to add a `""` before the current alt text to make it the right argument. I can add this to the documentation.

2023-07-31 20:59 UTC, igorkorenfeld commented on content/ux-guide/our-approach/index.md
> +    parent: ux-guide-approach
2 spaces

2023-07-31 20:59 UTC, igorkorenfeld commented on content/ux-guide/our-approach/meet-people-where-they-are.md
> +    parent: ux-guide-approach
2 Spaces

2023-07-31 20:59 UTC, igorkorenfeld commented on content/ux-guide/research/bias.md
> +    parent: ux-guide-research
2 Spaces

2023-07-31 20:59 UTC, igorkorenfeld commented on content/ux-guide/research/clarify-the-basics.md
> +    parent: ux-guide-research
2 Spaces

2023-07-31 20:59 UTC, igorkorenfeld commented on content/ux-guide/research/clarify-the-basics.md
> +    - [Stakeholders](https://product-guide.18f.gov/discover/stakeholders/#understand-your-key-stakeholders) (generally our agency partners)
Change to link replatformed guide

2023-07-31 20:59 UTC, igorkorenfeld commented on content/ux-guide/research/do.md
> +    parent: ux-guide-research
2 spaces

2023-07-31 20:59 UTC, igorkorenfeld commented on content/ux-guide/research/ethics.md
> +    parent: ux-guide-research
2 Spaces

2023-07-31 20:59 UTC, igorkorenfeld commented on content/ux-guide/research/ethics.md
> +- Acknowledge that all research is subject to [bias]({{ '../../research/bias/' | url }}), and actively work to counter it
Nothing you did here, but something I can't help but want to adjust as a product designer is the "it" on its own line here. Could make this
`counter&nbsp;it`

2023-07-31 20:59 UTC, igorkorenfeld commented on content/ux-guide/research/index.md
> +    parent: ux-guide-research
2 Spaces

2023-07-31 20:59 UTC, igorkorenfeld commented on content/ux-guide/research/make-research-actionable.md
> +    parent: ux-guide-research
2 spaces

2023-07-31 20:59 UTC, igorkorenfeld commented on content/ux-guide/research/plan.md
> +    parent: ux-guide-research
2 Spaces

2023-07-31 20:59 UTC, igorkorenfeld commented on content/ux-guide/research/privacy.md
> +    parent: ux-guide-research
2 Spaces

2023-07-31 21:14 UTC, AnitaYCheng commented
> Another thing I noticed is that a lot of the pages contain a "description" in the front matter, and I don't believe this is currently being used anywhere. Perhaps it should? If so we should make another ticket for it.

I assumed that would actually provide the page's meta description, because that's what it does in Jekyll. Adding it would be good for SEO!

2023-07-31 22:23 UTC, AnitaYCheng commented
I think the link checker is failing because of the resources pages I _haven't_ moved yet. Although it's also failing to find anchor links that seem to work for me.

2023-08-01 14:16 UTC, igorkorenfeld commented
Let's chat about the links, I think we can resolve most of them.

2023-08-01 21:16 UTC, igorkorenfeld approved these changes
This looks great, thanks for making all those changes!

2023-08-01 21:22 UTC, merged